[platformio]
src_dir = .

[env]
framework = arduino

[env:gps]
platform = espressif32
board = esp32dev
build_src_filter = +<gps/*>

[env:main]
platform = espressif32
board = esp32dev
build_src_filter = +<main/*>

[env:r-lora]
platform = espressif32
board = esp32dev
build_src_filter = +<R-LoRa/*>

[env:s-lora]
platform = espressif32
board = esp32dev
build_src_filter = +<S-LoRa/*>

[env:temps]
platform = espressif32
board = esp32dev
build_src_filter = +<temps/*>
lib_deps = 
	milesburton/DallasTemperature@^4.0.6
	paulstoffregen/OneWire@^2.3.8
