[platformio]
src_dir = .

[env]
framework = arduino

check_tool = clangtidy
check_flags = 
    clangtidy: --config-file=.clang-tidy
check_src_filters =
    +<boards/>
    +<shared/>

[env:gps]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/gps/*>

[env:main]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/main/*>

[env:r-lora]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/R-LoRa/*>

[env:s-lora]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/S-LoRa/*>

[env:temps]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/temps/*>
lib_deps = 
	milesburton/DallasTemperature@^4.0.6
	paulstoffregen/OneWire@^2.3.8
