[platformio]
src_dir = .

[env]
monitor_speed = 115200
monitor_filters = direct

framework = arduino
build_unflags = -std=gnu++11 -std=gnu++14
build_flags = 
    -I shared
    -D SERIAL_BAUD=${this.monitor_speed}
    -std=gnu++17

check_tool = clangtidy
check_flags = 
    clangtidy: --config-file=.clang-tidy
check_src_filters =
    +<boards/>
    +<shared/>

[env:gps]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/gps/*>

[env:main]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/main/*>

[env:r-lora]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/R-LoRa/*>

[env:s-lora]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/S-LoRa/*>

[env:temps]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/temps/*>
lib_deps = 
	milesburton/DallasTemperature@^4.0.6
	paulstoffregen/OneWire@^2.3.8



; not used in production
; just an example for you to see what each thing does
[env:example]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/example/*>


; note that this is just my testing ground,
; you do NOT need this
[env:testing-ground]
platform = espressif32
board = esp32dev
build_src_filter = +<boards/.test/*>
